[package]
name = "day23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
bitvector = "0.1.5"
crossbeam = "0.8.3"
crossbeam-deque = "0.8.4"
indexmap = "2.1.0"
indexset = "0.3.6"
